# HTTP内容替换代理服务器配置文件

# 服务器配置
server:
  host: "0.0.0.0"          # 监听地址
  port: 16565               # 监听端口

# 目标服务器配置

# 方式2: 多目标服务器负载均衡（推荐）
target:
  urls:                              # 多个目标服务器URL数组
    - "http://10.0.0.52:16501"
    - "http://10.0.0.52:16502"
    - "http://10.0.0.52:16503"
  timeout: 60s                       # 请求超时时间
  strategy: "round_robin"            # 负载均衡策略
#
#   # 健康检查配置
#   health_check:
#     enabled: true                    # 启用健康检查
#     interval: 30s                    # 检查间隔
#     path: "/health"                  # 健康检查路径
#     timeout: 5s                      # 健康检查超时

# 日志配置
logging:
  level: "info"            # 日志级别: debug, info, warn, error
  file: "logs/proxy.log"   # 日志文件路径

# 规则配置
rules:
  # 方式1: 单个规则文件（原有方式）
  #file: "configs/rules.yaml"  # 规则文件路径
  
  # 方式2: 多个规则文件（新增功能）
  files:
    - "configs/rules.yaml"     # 传统规则文件
    - "configs/easy01.yaml"    # 简单规则文件
  
  auto_reload: true           # 是否自动重载规则

# 调试配置
debug:
  enabled: true              # 是否启用调试模式
  show_original: false        # 是否显示原始请求内容
  show_modified: true        # 是否显示修改后请求内容
  show_rule_matches: true    # 是否显示规则匹配情况