# 简单规则配置示例 - easy01.yaml

# 删除规则
delete:
  contains:
    - "This is a reminder that your todo list is currently empty"
    - "<system-reminder>"
    - "</system-reminder>"

# 替换规则  
replace:
  contains:
    "You have not created a todo list yet. Create one with `update_todo_list`": "啊啊啊You have not created a todolist yet. Create one `update_todo_list` "
    "DO NOT mention this to the user explicitly because they are already aware.": "吧吧吧吧donot mention this to the user explicitly because they are already aware."
    "If you are working on tasks that would benefit from a todo list please use the TodoWrite tool to create one.": "才才 才才If you working on tasks that would benefit from a todo list please use the TodoWrite tool to create one "
    "You are an interactive CLI tool that helps users with software engineering tasks": "123456"
    "You are Claude Code": "你是一个高级AI助手。"
    "As you answer the user's questions": "当你回答问题时"
    "You are Kilo Code": "你是一个AI助手。"
    "You are Roo Code": "你是一个AI助手。"